build:
  stage: build
  only:
  - tags
  before_script:
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  script:
  - docker build -t ${CI_REGISTRY_IMAGE}:${PROJECT_TAG} .
  - docker run --rm ${CI_REGISTRY_IMAGE}:${PROJECT_TAG} /bin/bash -c 'npm install --only=dev && npm test'
  - docker push ${CI_REGISTRY_IMAGE}:${PROJECT_TAG}

variables:
  PROJECT_TAG: "13.2.2"
