build:
  stage: build
  script:
  - docker build -t ${CI_REGISTRY_IMAGE}:${PROJECT_TAG} .

test:
  stage: test
  script:
  - docker run --rm ${CI_REGISTRY_IMAGE}:${PROJECT_TAG} /bin/bash -c 'npm install --only=dev && npm test'

push:
  stage: deploy
  only:
  - master
  script:
  - docker push ${CI_REGISTRY_IMAGE}:${PROJECT_TAG}

variables:
  PROJECT_TAG: "8.0.1"
